services:
  frontend:
    image: wasserstiefel/iss-tracker-frontend:latest
    ports:
      - "80:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    image: wasserstiefel/iss-tracker-backend:latest
    ports:
      - "5000:5000"  
    restart: unless-stopped