---
- name: Configure EC2 instance
  hosts: all
  become: yes
  vars:
    COMPOSE_DIR: /app

  tasks:
    - name: Update yum cache
      yum:
        update_cache: yes

    - name: Install required packages
      yum:
        name:
          - docker
          - curl
          - python-pip
        state: present

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create app directory
      file:
        path: "{{ COMPOSE_DIR }}"
        state: directory
        mode: '0755'

    - name: Copy docker-compose.yml
      copy:
        src: "{{ playbook_dir }}/../docker-compose.yml"
        dest: "{{ COMPOSE_DIR }}/docker-compose.yml"
        mode: '0644'

    - name: Log into Docker Hub
      shell: docker login -u {{ docker_username }} -p {{ docker_password }}
      no_log: true
      changed_when: false

    # Skip Docker Compose installation and use Docker directly with compose subcommand
    - name: Deploy with Docker directly
      shell: |
        cd {{ COMPOSE_DIR }}
        docker compose up -d || docker-compose up -d
      register: compose_result
      changed_when: "'Creating' in compose_result.stdout or 'Starting' in compose_result.stdout"
      
    - name: Display deployment result
      debug:
        var: compose_result.stdout_lines