---
- name: Configure EC2 instance
  hosts: all
  become: yes
  tasks:
    - name: Update yum cache and upgrade packages
      yum:
        name: '*'
        state: latest
        update_cache: yes

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'
        owner: root
        group: root

    - name: Ensure Docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create app directory
      file:
        path: /app
        state: directory
        mode: '0755'

    - name: Copy frontend directory
      copy:
        src: "{{ playbook_dir }}/../frontend/"
        dest: /app/frontend/
        mode: preserve

    - name: Copy backend directory
      copy:
        src: "{{ playbook_dir }}/../backend/"
        dest: /app/backend/
        mode: preserve

    - name: Copy docker-compose.yml
      copy:
        src: "{{ playbook_dir }}/../docker-compose.yml"
        dest: /app/docker-compose.yml
        mode: '0644'

    - name: Run docker compose with timeout
      shell: /usr/local/bin/docker-compose up -d
      args:
        chdir: /app
      timeout: 300  # 5-minute timeout to prevent indefinite hangs
      register: docker_compose_output

    - name: Debug docker compose output
      debug:
        var: docker_compose_output
      when: docker_compose_output.failed or docker_compose_output.rc != 0