---
- name: Configure EC2 instance
  hosts: all
  become: yes
  vars:
    COMPOSE_DIR: /app
    DOCKER_COMPOSE_VERSION: "v2.25.0"

  tasks:
    - name: Update yum cache
      yum:
        update_cache: yes

    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Install curl for Docker Compose
      yum:
        name: curl
        state: present

    - name: Install Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ DOCKER_COMPOSE_VERSION }}/docker-compose-linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Log into Docker Hub
      command: docker login -u {{ docker_username }} -p {{ docker_password }}
      no_log: true

    - name: Create app directory
      file:
        path: "{{ COMPOSE_DIR }}"
        state: directory

    - name: Copy docker-compose.yml
      copy:
        src: "{{ playbook_dir }}/../docker-compose.yml"
        dest: "{{ COMPOSE_DIR }}/docker-compose.yml"

    - name: Start containers
      docker_compose:
        project_src: "{{ COMPOSE_DIR }}"
        state: present